### ISSUE TITLE
Crash at launch 

### ISSUE THREAD

**Issue by LotuxPunk** [gunnerwolf/TeslaCoils#10]
Hello, can you help me please ? :)

http://pastebin.com/Y8TTbNt2

[crash-2016-08-15_15.03.31-server.txt](https://github.com/gunnerwolf/TeslaCoils/files/418077/crash-2016-08-15_15.03.31-server.txt)

**Comment by dylanrenwick** [comment]
Storage Drawers is causing the crash, report it on their github here https://github.com/jaquadro/StorageDrawers
