### ISSUE TITLE
Crash when machine attached to coil is broken

### ISSUE THREAD

**Issue by F4ndroid** [gunnerwolf/TeslaCoils#2]
http://pastebin.com/NB1yAnZx
Also corrupts the save.

**Comment by dylanrenwick** [comment]
If you could tell me what machine it was attached to, that'd be helpful for testing, as I'm fairly certain this crash was fixed before release.

**Comment by F4ndroid** [comment]
Induction charger from http://minecraft.curseforge.com/projects/induction-charger
Tesla Coils version: 0.1.2.0
Induction Charger version: 1.1.0
Tesla version: 1.2.0.34

**Comment by dylanrenwick** [comment]
After testing it myself and checking the error, this is a problem with Induction Charger, I intend to submit a PR to fix the issue shortly, and I assume shadow will push out a hotfix build after that.
