### ISSUE TITLE
Unable to transfer power to Tesla consuming TechReborn machines

### ISSUE THREAD

**Issue by Sethgoldfox** [gunnerwolf/TeslaCoils#4]
![2016-07-22_09 09 20](https://cloud.githubusercontent.com/assets/8475136/17063541/b1c7b8fe-4fec-11e6-85b3-1c1e3bfcc778.png)

Hello, there seems to be an issue with transferring power between Tech Reborn machines using the Tesla Coil. The power will drain from the generating machine, but will not be transferred to the consuming machine. This was tested with the Tech Reborn generator and electric furnace. I tried placing the coil on each side of the furnace, but to no avail.

Mod Versions Used:
Tesla Coils 0.1.2.0
Tech Reborn-1.10.2-1.3.4.11
Reborn Core-1.10.2-2.5.5.3

**Comment by dylanrenwick** [comment]
I believe this is an issue with TechReborn's Tesla compat being incomplete, however I will investigate and in the event it is TR's issue, I'll likely send over a PR to fix their Tesla compat.
