### ISSUE TITLE
Crash when linking Tesla Coil attached to a Solar Panel

### ISSUE THREAD

**Issue by Sethgoldfox** [gunnerwolf/TeslaCoils#5]
![04c33a24877f4132bf3fc640e6efb88a](https://cloud.githubusercontent.com/assets/8475136/17068516/3b81c094-5006-11e6-87f8-ef6373cae8b4.png)

This crash occurred while trying to link a Tesla Coil attached to one of Solar Village's Solar panels using the Tuning Rod. The Coil had earlier been attached and linked without issue, the problem arose when one was destroyed and replaced. Crash log: http://pastebin.com/HhtrFnai

**Comment by dylanrenwick** [comment]
What machine is the other Tesla Coil attached to?

**Comment by Sethgoldfox** [comment]
A Tech Reborn Macerator.

**Comment by Sethgoldfox** [comment]
It's worth noting that I cannot replicate the crash on a new World. However, the issue persists on the old World.

**Comment by dylanrenwick** [comment]
Given where the crash happened (onTuningToolUse) the only things I can think of is that the Tuning Tool's NBT was broken, or that for some reason the Solar Panel's Tesla Coil failed to find the Tile Entity of the Macerator's Tesla Coil, both of which shouldn't really happen ever, and would be difficult to replicate in a "natural" circumstance (obviously it's easy to intentionally delete the Tesla Coil's Tile Entity or screw with the tool's NBT to force it)

I'll investigate further and add some checks to at least prevent a crash happening if either of those issues arise.
