### ISSUE TITLE
Tesla changed their modid

### ISSUE THREAD

**Issue by LlubNek** [gunnerwolf/TeslaCoils#7]
The Tesla API changed their modid from "Tesla" (capitalized) to "tesla" (lower case), which breaks a dependency for your mod.

**Comment by dylanrenwick** [comment]
As per the Tesla curseforge page:

`Alpha and beta releases are intended for mod authors and testers. Mods that support Tesla should only target full releases! Using an alpha build may crash mods that require it!`

In other words, until the release build of Tesla changes their modid (which Darkhax assures me will be soon) I'm not changing it.

The reason for this is I have to depend on _either_ `Tesla` or `tesla`, so if I change it to `tesla` now, people following the Release build rule won't be able to use Tesla Coils.

So I've made the change in the code, but I'll be waiting on releasing the next update to TC until Tesla's release build updates.

**Comment by ruyanve** [comment]
Looks like they put a stable release build. Looking forward to using your mod, cheers! :-)
